flag_management:
  default_rules:
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
  individual_flags:
    - name: xcm-sdk
      paths:
        - packages/sdk
      carryforward: true
    - name: xcm-analyser
      paths:
        - packages/xcm-analyser
      carryforward: true
    - name: xcm-router
      paths:
        - packages/xcm-router
      carryforward: true
    - name: xcm-api
      paths:
        - apps/xcm-api
      carryforward: true
    - name: visualizator-be
      paths:
        - apps/visualizator-be
      carryforward: true

comment:
  show_carryforward_flags: true
