name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: |
          touch .env
          echo GH_COMMIT_SHA="${{ github.event.pull_request.head.sha }}" >> .env
          echo CODECOV_TOKEN="${{ secrets.CODECOV_TOKEN }}" >> .env
      - run: pnpm install
      - run: pnpm build
      - run: pnpm compile
      - run: pnpm format:check
      - run: pnpm lint:check
      - run: pnpm test:cov
      - name: Upload XCM SDK coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/sdk
          flags: xcm-sdk
          fail_ci_if_error: false
          verbose: true
      - name: Upload XCM Analyser coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/xcm-analyser
          flags: xcm-analyser
          fail_ci_if_error: false
          verbose: true
      - name: Upload XCM Router coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: packages/xcm-router
          flags: xcm-router
          fail_ci_if_error: false
          verbose: true
      - name: Upload Visualizator BE coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: apps/visualizator-be
          flags: visualizator-be
          fail_ci_if_error: false
          verbose: true
      - name: Upload XCM API coverage report to Codecov
        uses: codecov/codecov-action@v4.5.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: apps/xcm-api
          flags: xcm-api
          fail_ci_if_error: false
          verbose: true
