name: Deploy Visualizator Backend

on:
  push:
    branches:
      - main
  # Enables manual trigger of the workflow
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ~/xcm-tools
    steps:
      - run: git pull
      - run: pnpm install
      - run: pnpm build
      - name: Restart PM2 process
        run: pm2 restart visualizator-be
        env:
          PM2_HOME: /root/.pm2
